### ISSUE TITLE
Large document fix

### ISSUE THREAD

**Issue by jamescalam** [aurelio-labs/semantic-chunkers#6]
## Large documents chunking memory error

@ashraq1455 encountered an error where if a document were sufficiently large enough the worker would shutdown. The suspected cause was due to our `semantic_chunkers.StatisticalChunker` encoding sentence embeddings and storing all of them in-memory at the same time for the chunking methodology to run.

The proposed solution here would be to add a “rolling window” of focus that embeds a maximum number of sentences at any one time. This fix should be applied to both `ConsecutiveChunker` and `StatisticalChunker` in the `semantic_chunkers` library.

**Comment by ashraq1455** [comment]
#7
